(require :asdf)
(push #P"./" asdf:*central-registry*)
(push #P"./src/" asdf:*central-registry*)
(dolist (sd (directory "vendor/*/")) (pushnew sd asdf:*central-registry*))
(asdf:load-system :ymacs)
(setf ymacs::*store-path-override*
      (merge-pathnames ".yggterm/scratchpad/ymacs-ribbon/probe-store.sqlite3"
                       (user-homedir-pathname)))
(when (probe-file ymacs::*store-path-override*)
  (delete-file ymacs::*store-path-override*))
(ymacs::store-open)
(format t "*profile* = ~a~%" ymacs::*profile*)
(format t "*store* = ~a~%" (if ymacs::*store* "open" "nil"))
(let ((buf (ymacs::make-new-buffer "*persist-me*" "survives anything")))
  (format t "buffer id = ~a~%" (ymacs::buffer-id buf))
  (format t "exists-p = ~a~%" (ymacs::store-buffer-exists-p (ymacs::buffer-id buf)))
  (format t "get-buffer values = ~a~%" (multiple-value-list (ymacs::store-get-buffer (ymacs::buffer-id buf))))
  (format t "content = ~a~%" (ymacs::store-buffer-content (ymacs::buffer-id buf))))
(sb-ext:quit)
