(require :asdf)
(push #P"./" asdf:*central-registry*)
(push #P"./src/" asdf:*central-registry*)
(dolist (sd (directory "vendor/*/")) (pushnew sd asdf:*central-registry*))
(asdf:load-system :ymacs)
(handler-case (ymacs::init-default-keymaps)
  (error (e) (format t "INIT-ERROR: ~a~%" e)))
(format t "keymaps table: ~a~%" (hash-table-count ymacs::*elisp-keymaps*))
(let ((m (gethash "global" ymacs::*elisp-keymaps*)))
  (format t "global map: ~a~%" (if m (hash-table-count (elisp-keymap-bindings m)) "NIL"))
  (when m
    (let ((dead nil))
      (maphash (lambda (k v)
                 (when (and (symbolp v) (not (fboundp v)))
                   (push (cons k v) dead)))
               (elisp-keymap-bindings m))
      (format t "DEAD: ~a~%" dead))))
(sb-ext:quit)
